create database Hibernate_Registration_System;

create table PERSON (
                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                        first_name VARCHAR(20) default NULL,
                        middle_name VARCHAR(20) default NULL,
                        last_name VARCHAR(20) default NULL,
                        suffix VARCHAR(5) default NULL,
                        title VARCHAR(20) default NULL,
                        birthday DATE default NULL,
                        unit_no  VARCHAR(20) default NULL,
                        street  VARCHAR(30) default NULL,
                        baranggay  VARCHAR(30) default NULL,
                        subdivision  VARCHAR(30) default NULL,
                        municipality  VARCHAR(30) default NULL,
                        province  VARCHAR(30) default NULL,
                        zipcode  INT default NULL,
                        gwa     DOUBLE PRECISION  default NULL,
                        date_hired     DATE  default NULL,
                        currently_employed VARCHAR(50)  default NULL,
                        PRIMARY KEY (id)
);