create table CONTACT(
    contact_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    contact_type VARCHAR(9) default null,
    contact_info VARCHAR(50) default null,
    person_id BIGINT default null references PERSON(id) on delete cascade,
    PRIMARY KEY(contact_id)
);

create table ROLES(
    role_id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_type VARCHAR(50)
);

INSERT INTO ROLES (role_type) values ('Admin');
INSERT INTO ROLES (role_type) values ('Developer');
INSERT INTO ROLES (role_type) values ('Quality Assurance');
INSERT INTO ROLES (role_type) values ('Business Analyst');
INSERT INTO ROLES (role_type) values ('Finance Officer');

create table PERSON_ROLE(
    person_id BIGINT,
    role_id BIGINT,
    PRIMARY KEY(person_id, role_id),
    FOREIGN KEY(person_id) REFERENCES PERSON(id) ON DELETE CASCADE,
    FOREIGN KEY(role_id) REFERENCES ROLES(role_id) ON DELETE CASCADE
);