ALTER TABLE PERSON
ADD COLUMN employee_reference VARCHAR(20) DEFAULT NULL;


ALTER TABLE contact
ADD COLUMN contact_order INT DEFAULT NULL;


ALTER TABLE roles
ADD COLUMN is_active BOOLEAN DEFAULT NULL;