create table Person (
                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                        name VARCHAR(100) default NULL,
                        address  VARCHAR(100) default NULL,
                        birthday DATE default NULL,
                        gwa     DOUBLE PRECISION  default NULL,
                        date_hired     DATE  default NULL,
                        currently_employed     VARCHAR(50)  default NULL,
                        landline_number     INTEGER  default NULL,
                        mobile_number     INTEGER  default NULL,
                        email    VARCHAR(50) default NULL,
                        roles VARCHAR(50) default NULL,
                        PRIMARY KEY (id)
);